export const FETCH_APARTMENTS_REQUEST = 'FETCH_APARTMENTS_REQUEST';
export const FETCH_APARTMENTS_SUCCESS = 'FETCH_APARTMENTS_SUCCESS';
export const FETCH_APARTMENTS_FAILURE = 'FETCH_APARTMENTS_FAILURE';

// cart
export const TOGGLE_CART = 'TOGGLE_CART';
export const ADD_ITEM_TO_CARD = 'ADD_ITEM_TO_CARD';
export const INCREMENT_ITEM = 'INCREMENT_ITEM';
export const DECREMENT_ITEM = 'DECREMENT_ITEM';
export const REMOVE_ITEM_IN_CART = 'REMOVE_ITEM_IN_CART';
export const REMOVE_ALL_ITEMS_IN_CART = 'REMOVE_ALL_ITEMS_IN_CART';
