export const FETCH_APARTMENTS_REQUEST = 'FETCH_APARTMENTS_REQUEST';
export const FETCH_APARTMENTS_SUCCESS = 'FETCH_APARTMENTS_SUCCESS';
export const FETCH_APARTMENTS_FAILURE = 'FETCH_APARTMENTS_FAILURE';

export const ADD_ITEM_TO_CARD = 'ADD_ITEM_TO_CARD';
